name: Greet-someone
inputs:
  name:
    description: "Someone"
    required: true
  language:
    description: "Language of greeting"
    required: true
    default: "en"
outputs:
  greeted:
    value: ${{ steps.check-status.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Print a greeting in the specified language
      run: echo "Hello world,what's happening"
      shell: bash
    - name: Print the current date and runner OS
      run: echo "Current runner is :${{ runner.os }}"
      shell: bash
    - name: greeting status
      id: check-status
      run: echo "status=true" >> $GITHUB_OUTPUT
