name: call-build

on:
  push:
    branches: [main]

jobs:
  call-reuseable-workflow:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app-name: "my-web-app"
      environment: "production"

    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
