# added correct name
name: call-build

on:
  push:
    branches: [main]

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app-name: "my-web-app"
      environment: "production"

    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  use-result:
    needs: call-reusable
    runs-on: ubuntu-latest
    steps:
      - name: Get from reusealbe job
        run: echo "final version is ${{ needs.call-reusable.outputs.result}}"
