name: create-pr

on:
  pull_request:
    branches:
      - main

jobs:
  initiate-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: check code 
      uses: actions/checkout@v4

    - name: print message
      run: echo "pull_request is created"
