name: reuseable-workflow

on:
  workflow_call:
    inputs:
      app-name:
        type: string
        required: true

      environment:
        type: string
        required: true
        default: staging

    secrets:
      DOCKERHUB_TOKEN:
        required: true
    outputs:
      build:
        description: "print app version"
        version: ${{ jobs.reuse-workflow.outputs.job-outputs }}
    
jobs:
  reuse-workflow:
    runs-on: ubuntu-latest
    outputs:
      job-outputs: ${{ steps.gen-version.outputs.version }}
    steps:
      - name: checkout the code 
        uses: actions/checkout@v4

      - name: Prints Building <app_name> for <environment>
        run: echo "Building ${{ inputs.app-name }} for ${{ inputs.environment }}."

      - name: Prints Docker token
        run: echo "Docker token is set true"
      
      - name: print version of build
        id: gen-version
        run: echo "version=v1.0 ${GITHUB_SHA::7}" >> $GITHUB_OUTPUT


