name: run-greet-action

on:
  push:
    branches: [ main ]

jobs:
  greet-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: select composite action path
        id: greet
        uses: ./.github/actions/setup-and-greet
        with:
          name: "Mona"
          language: "en"

      - name: check greeting status
        run: echo "Greeting status is ${{ steps.greet.outputs.greeted }}"
