steps:
  - name: select composit action path
    id: greet
    uses: ./.github/actions/setup-and-greet
    with:
      name: 'Mona'
      language: "en"

  - name: check greeting status
    run: echo " Greeting status is ${{ steps.greet.output.greeted }}"
